package com.dyc.xiaohashu.id.generator.core.segment;

import com.dyc.xiaohashu.id.generator.core.IdGenerator;

/**
 * Contract for database segment ID generators.
 */
public interface SegmentIdGenerator extends IdGenerator {

    /**
     * Returns the current local segment.
     *
     * @return current segment
     */
    IdSegment currentSegment();

    /**
     * Returns the number of IDs generated by this instance.
     *
     * @return generated IDs
     */
    long generatedTotal();

    /**
     * Returns the number of segments fetched by this instance.
     *
     * @return allocated segments
     */
    long segmentAllocatedTotal();

    /**
     * Returns the number of segment fetch failures observed by this instance.
     *
     * @return segment fetch failures
     */
    long segmentFetchFailureTotal();
}
