<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.dyc.xiaohashu.kv</groupId>
        <artifactId>xiaohashu-kv</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>xiaohashu-kv-biz</artifactId>
    <packaging>jar</packaging>

    <name>xiaohashu-kv-biz</name>
    <version>${revision}</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- 业务接口日志组件 -->
        <dependency>
            <groupId>com.dyc</groupId>
            <artifactId>xiaoha-spring-boot-starter-biz-operationlog</artifactId>
        </dependency>

        <!-- Jackson 组件 -->
        <dependency>
            <groupId>com.dyc.framework.jackson</groupId>
            <artifactId>xiaoha-spring-boot-starter-jackson</artifactId>
        </dependency>

        <dependency>
            <groupId>com.dyc</groupId>
            <artifactId>xiaoha-common</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- Knife4j 接口文档 -->
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- 服务发现 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- Cassandra 存储 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-cassandra</artifactId>
        </dependency>
        <dependency>
            <groupId>com.dyc.xiaohashu.kv</groupId>
            <artifactId>xiaohashu-kv-api</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
