<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.dyc</groupId>
        <artifactId>xiaohashu-search</artifactId>
        <version>${revision}</version>
    </parent>

    <groupId>com.dyc.xiaohashu.search</groupId>
    <artifactId>xiaohashu-search-api</artifactId>
    <packaging>jar</packaging>

    <name>xiaohashu-search-api</name>
    <description>搜索服务 RPC层，供其他服务调用</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.dyc</groupId>
            <artifactId>xiaoha-common</artifactId>
        </dependency>
    </dependencies>
</project>
