package com.dyc.xiaohashu.id.generator.core.snowflake;

import com.dyc.xiaohashu.id.generator.core.IdGenerator;
import com.dyc.xiaohashu.id.generator.core.machine.MachineLease;

/**
 * Contract for Snowflake ID generators.
 */
public interface SnowflakeIdGenerator extends IdGenerator {

    /**
     * Returns the immutable Snowflake bit layout.
     *
     * @return Snowflake config
     */
    SnowflakeConfig config();

    /**
     * Returns the current machine lease used by this generator.
     *
     * @return machine lease
     */
    MachineLease machineLease();

    /**
     * Returns the latest timestamp used by this generator, in epoch milliseconds.
     *
     * @return last generated timestamp
     */
    long lastTimestamp();

    /**
     * Returns the number of IDs generated by this instance.
     *
     * @return generated IDs
     */
    long generatedTotal();

    /**
     * Returns the number of local clock rollback events observed by this instance.
     *
     * @return clock rollback count
     */
    long clockBackwardsTotal();

    /**
     * Returns the number of times the local sequence exhausted in one millisecond.
     *
     * @return sequence overflow count
     */
    long sequenceOverflowTotal();
}
