package com.dyc.xiaohashu.id.generator.spring.boot.metrics;

import com.dyc.xiaohashu.id.generator.core.machine.MachineLease;
import com.dyc.xiaohashu.id.generator.core.segment.DefaultSegmentPrefetchScheduler;
import com.dyc.xiaohashu.id.generator.core.segment.IdSegment;
import com.dyc.xiaohashu.id.generator.core.segment.SegmentChainIdGenerator;
import com.dyc.xiaohashu.id.generator.core.segment.SegmentIdGenerator;
import com.dyc.xiaohashu.id.generator.core.segment.SegmentPrefetchScheduler;
import com.dyc.xiaohashu.id.generator.core.snowflake.SnowflakeIdGenerator;
import com.dyc.xiaohashu.id.generator.spring.boot.lifecycle.SnowflakeLeaseLifecycle;
import io.micrometer.core.instrument.FunctionCounter;
import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Tags;
import io.micrometer.core.instrument.binder.MeterBinder;

import java.util.List;
import java.util.Objects;

/**
 * Micrometer binder for distributed ID generator runtime state.
 */
public class DistributedIdMeterBinder implements MeterBinder {

    private final List<SnowflakeIdGenerator> snowflakeIdGenerators;
    private final List<SnowflakeLeaseLifecycle> snowflakeLeaseLifecycles;
    private final List<SegmentIdGenerator> segmentIdGenerators;
    private final List<SegmentChainIdGenerator> segmentChainIdGenerators;
    private final List<SegmentPrefetchScheduler> segmentPrefetchSchedulers;

    public DistributedIdMeterBinder(
            List<SnowflakeIdGenerator> snowflakeIdGenerators,
            List<SnowflakeLeaseLifecycle> snowflakeLeaseLifecycles,
            List<SegmentIdGenerator> segmentIdGenerators,
            List<SegmentChainIdGenerator> segmentChainIdGenerators,
            List<SegmentPrefetchScheduler> segmentPrefetchSchedulers
    ) {
        this.snowflakeIdGenerators = List.copyOf(Objects.requireNonNull(snowflakeIdGenerators, "snowflakeIdGenerators must not be null"));
        this.snowflakeLeaseLifecycles = List.copyOf(Objects.requireNonNull(snowflakeLeaseLifecycles, "snowflakeLeaseLifecycles must not be null"));
        this.segmentIdGenerators = List.copyOf(Objects.requireNonNull(segmentIdGenerators, "segmentIdGenerators must not be null"));
        this.segmentChainIdGenerators = List.copyOf(Objects.requireNonNull(segmentChainIdGenerators, "segmentChainIdGenerators must not be null"));
        this.segmentPrefetchSchedulers = List.copyOf(Objects.requireNonNull(segmentPrefetchSchedulers, "segmentPrefetchSchedulers must not be null"));
    }

    @Override
    public void bindTo(MeterRegistry registry) {
        snowflakeIdGenerators.forEach(generator -> bindSnowflake(registry, generator));
        snowflakeLeaseLifecycles.forEach(lifecycle -> bindSnowflakeLeaseLifecycle(registry, lifecycle));
        segmentIdGenerators.forEach(generator -> bindSegment(registry, generator));
        segmentChainIdGenerators.forEach(generator -> bindSegmentChain(registry, generator));
        segmentPrefetchSchedulers.forEach(scheduler -> bindSegmentPrefetchScheduler(registry, scheduler));
    }

    private void bindSnowflake(MeterRegistry registry, SnowflakeIdGenerator generator) {
        MachineLease lease = generator.machineLease();
        Tags tags = Tags.of("namespace", lease.namespace(), "machine_id", Integer.toString(lease.machineId()));
        FunctionCounter.builder("xiaohashu.id.snowflake.generated", generator, SnowflakeIdGenerator::generatedTotal)
                .description("Snowflake IDs generated by this instance")
                .tags(tags)
                .register(registry);
        FunctionCounter.builder("xiaohashu.id.snowflake.clock.backwards", generator, SnowflakeIdGenerator::clockBackwardsTotal)
                .description("Local clock rollback events observed by the Snowflake generator")
                .tags(tags)
                .register(registry);
        FunctionCounter.builder("xiaohashu.id.snowflake.sequence.overflow", generator, SnowflakeIdGenerator::sequenceOverflowTotal)
                .description("Snowflake sequence overflow events")
                .tags(tags)
                .register(registry);
        Gauge.builder("xiaohashu.id.snowflake.machine.id", generator, value -> value.machineLease().machineId())
                .description("Current Snowflake machine ID")
                .tags(tags)
                .register(registry);
        Gauge.builder("xiaohashu.id.snowflake.lease.expires.at", generator, value -> value.machineLease().leaseExpiresAt().toEpochMilli())
                .description("Current Snowflake machine lease expiration time in epoch milliseconds")
                .tags(tags)
                .register(registry);
    }

    private void bindSnowflakeLeaseLifecycle(MeterRegistry registry, SnowflakeLeaseLifecycle lifecycle) {
        Tags tags = Tags.of("component", "snowflake");
        FunctionCounter.builder("xiaohashu.id.snowflake.heartbeat.success", lifecycle, SnowflakeLeaseLifecycle::heartbeatSuccessTotal)
                .description("Successful Snowflake machine lease heartbeats")
                .tags(tags)
                .register(registry);
        FunctionCounter.builder("xiaohashu.id.snowflake.heartbeat.failure", lifecycle, SnowflakeLeaseLifecycle::heartbeatFailureTotal)
                .description("Failed Snowflake machine lease heartbeats")
                .tags(tags)
                .register(registry);
        FunctionCounter.builder("xiaohashu.id.snowflake.lease.lost", lifecycle, SnowflakeLeaseLifecycle::leaseLostTotal)
                .description("Snowflake machine lease lost events")
                .tags(tags)
                .register(registry);
        FunctionCounter.builder("xiaohashu.id.snowflake.lease.release.failure", lifecycle, SnowflakeLeaseLifecycle::releaseFailureTotal)
                .description("Failed Snowflake machine lease release operations during shutdown")
                .tags(tags)
                .register(registry);
        Gauge.builder("xiaohashu.id.snowflake.heartbeat.consecutive.failures", lifecycle, SnowflakeLeaseLifecycle::consecutiveHeartbeatFailures)
                .description("Consecutive heartbeat failures since the latest success")
                .tags(tags)
                .register(registry);
        Gauge.builder("xiaohashu.id.snowflake.lifecycle.running", lifecycle, value -> value.isRunning() ? 1 : 0)
                .description("Whether the Snowflake lease lifecycle is running")
                .tags(tags)
                .register(registry);
    }

    private void bindSegment(MeterRegistry registry, SegmentIdGenerator generator) {
        IdSegment currentSegment = generator.currentSegment();
        String type = generator instanceof SegmentChainIdGenerator ? "segment-chain" : "segment";
        Tags tags = Tags.of("type", type, "namespace", currentSegment.namespace(), "tag", currentSegment.tag());
        FunctionCounter.builder("xiaohashu.id.segment.generated", generator, SegmentIdGenerator::generatedTotal)
                .description("Segment IDs generated by this instance")
                .tags(tags)
                .register(registry);
        FunctionCounter.builder("xiaohashu.id.segment.allocated", generator, SegmentIdGenerator::segmentAllocatedTotal)
                .description("Segments fetched by this instance")
                .tags(tags)
                .register(registry);
        FunctionCounter.builder("xiaohashu.id.segment.fetch.failure", generator, SegmentIdGenerator::segmentFetchFailureTotal)
                .description("Segment fetch failures observed by this instance")
                .tags(tags)
                .register(registry);
        Gauge.builder("xiaohashu.id.segment.current.remaining", generator, value -> value.currentSegment().remaining())
                .description("Remaining IDs in the current local segment")
                .tags(tags)
                .register(registry);
    }

    private void bindSegmentChain(MeterRegistry registry, SegmentChainIdGenerator generator) {
        IdSegment currentSegment = generator.currentSegment();
        Tags tags = Tags.of("namespace", currentSegment.namespace(), "tag", currentSegment.tag());
        FunctionCounter.builder("xiaohashu.id.segment.chain.prefetch.success", generator, SegmentChainIdGenerator::prefetchSuccessTotal)
                .description("Successful segment-chain background prefetch runs")
                .tags(tags)
                .register(registry);
        FunctionCounter.builder("xiaohashu.id.segment.chain.prefetch.failure", generator, SegmentChainIdGenerator::prefetchFailureTotal)
                .description("Failed segment-chain background prefetch runs")
                .tags(tags)
                .register(registry);
        Gauge.builder("xiaohashu.id.segment.chain.distance", generator, SegmentChainIdGenerator::chainDistance)
                .description("Current segment-chain distance between head and tail")
                .tags(tags)
                .register(registry);
        Gauge.builder("xiaohashu.id.segment.chain.prefetch.distance", generator, SegmentChainIdGenerator::prefetchDistance)
                .description("Adaptive segment-chain prefetch distance")
                .tags(tags)
                .register(registry);
        Gauge.builder("xiaohashu.id.segment.chain.closed", generator, value -> value.closed() ? 1 : 0)
                .description("Whether the segment-chain generator is closed")
                .tags(tags)
                .register(registry);
    }

    private void bindSegmentPrefetchScheduler(MeterRegistry registry, SegmentPrefetchScheduler scheduler) {
        if (scheduler instanceof DefaultSegmentPrefetchScheduler defaultScheduler) {
            Tags tags = Tags.of("component", "segment-prefetch-scheduler");
            FunctionCounter.builder("xiaohashu.id.segment.prefetch.scheduler.failure", defaultScheduler, DefaultSegmentPrefetchScheduler::failedRunTotal)
                    .description("Failed background job executions in the shared segment prefetch scheduler")
                    .tags(tags)
                    .register(registry);
            Gauge.builder("xiaohashu.id.segment.prefetch.scheduler.jobs", defaultScheduler, DefaultSegmentPrefetchScheduler::registeredJobCount)
                    .description("Registered background segment prefetch jobs")
                    .tags(tags)
                    .register(registry);
            Gauge.builder("xiaohashu.id.segment.prefetch.scheduler.closed", defaultScheduler, value -> value.closed() ? 1 : 0)
                    .description("Whether the shared segment prefetch scheduler is closed")
                    .tags(tags)
                    .register(registry);
        }
    }
}
